[book]
title = "Asynchronous Programming in Rust 日本語版"
authors = ["Taylor Cramer"]
language = "ja"

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://github.com/masan4444/async-book-ja"
site-url = "/async-book-ja/"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
